package com.elemental.licitapp.SeguimientoProceso.domain.enums;

public enum TipoEventoSeguimiento {
    OFERTA_PRESENTADA,
    PLAZO_SUBSANACION_ABIERTO,
    SUBSANACION_PRESENTADA,
    INFORME_EVALUACION_PRELIMINAR,
    OBSERVACIONES_AL_INFORME,
    INFORME_EVALUACION_DEFINITIVO,
    AUDIENCIA_PROGRAMADA,
    AUDIENCIA_REALIZADA,
    RESOLUCION_ADJUDICACION,
    DECLARATORIA_DESIERTA,
    OTRO,
}
