spring.profiles.include=local
spring.application.name=licitapp

# Configuracion de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/licitapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracion del path base para los endpoints
server.servlet.context-path=/api/v1

#SECOP
secop.base-url=https://www.datos.gov.co/resource/p6dx-8zbt.json
secop.app-token=${SECOP_APP_TOKEN}
secop.page-size-default=10

# Spring AI OpenAI configuration
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.temperature=0.0

# Spring AI Ollama configuration (Local)
# Usaremos esto para generar los vectores de 100 paginas GRATIS
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text
# Si quisieras usar Chat local, descomenta esto:
# spring.ai.ollama.chat.options.model=llama3.1

# Configuracion de subida de archivos (Multipart)
# Tama�o maximo de cada archivo individual (por defecto 1MB)
spring.servlet.multipart.max-file-size=50MB
# Tama�o maximo de la peticion completa (por defecto 10MB)
spring.servlet.multipart.max-request-size=50MB

# Timeouts para procesamiento largo de documentos
server.tomcat.connection-timeout=120000
spring.mvc.async.request-timeout=120000